### ISSUE TITLE
format hex is too strict

### ISSUE THREAD

**Issue by cpsievert** [cpsievert/colourPalette#4]
[This check](https://github.com/cpsievert/colourPalette/blob/master/R/utils.R#L15-L17) is too strict...any ideas @daattali?

``` r
> colourPalette:::formatHEXsingle("#FF0000FF")
Error: #FF0000FF is not a valid colour
> scales::show_col("#FF0000FF")
```

**Comment by daattali** [comment]
The javascript library I built doesn't support opacity. I couldn't think of a nice way to add that feature without having weird behaviour and I didn't want to add a feature that's not 100% good so I just didn't add it

see https://github.com/daattali/shinyjs/issues/19 (though I didn't give any details there as to the problems it would present)

**Comment by cpsievert** [comment]
OK, thanks. I don't think that will be a big problem for my purposes

**Comment by cpsievert** [comment]
I'm guessing it doesn't support rgb() specification either?

**Comment by daattali** [comment]
formatHEX is to return a canonical representation of a a HEX colour
representation. You can easily convert a rgb(x, y, z) into HEX with
rgb(x,y,z,maxColorValue = 255)

---

http://deanattali.com

**Comment by cpsievert** [comment]
I was curious because I send colors to plotly.js from R using rgb()/rgba() format. I'm pretty sure I can workaround that, though.

**Comment by daattali** [comment]
rgba unfortunately won't work sorry!

---

http://deanattali.com
